exclude:
  - Makefile
  - README.md

collections:
  - name: posts
    folder: _posts
  - name: docs
    folder: _docs/user
  - name: twig-filters
    folder: _docs/twig

data:
  - _data

pageviews:
  - _pages

theme: corcra
debug: true

title: stakx - Yet Another Static Website Generator
categories:
    - announcements
    - releases
    - tutorials
