exclude:
  - README.md
  - feed.xml
  - /.html$/
  - yarn.lock

collections:
  - name: posts
    folder: _posts
  - name: docs
    folder: _docs

pageviews:
  - _pages

theme: corcra

title: stakx - Yet Another Static Website Generator
