exclude:
  - README.md
  - feed.xml
  - /.html$/
  - yarn.lock

collections:
  - name: docs
    folder: _docs

pageviews:
  - _pages

theme: corcra
debug: true

# Site Configuration
title: stakx - Yet Another Static Website Generator
